# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-02-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='description',
            field=models.TextField(default=' description default text'),
        ),
    ]
