# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='HACKER'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='INDIA', max_length=120),
        ),
    ]
