# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='INDIA', max_length=120, null=True),
        ),
    ]
